services:
    sidus_eav_model.denormalizer.data:
        parent: serializer.normalizer.object
        class: Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer
        arguments:
            - '@sidus_eav_model.family.registry'
            - '@doctrine'
            - '@sidus_eav_model.serializer.entity_provider'
            - '%sidus_eav_model.denormalizer.data.ignored_attributes%'
        tags:
            - { name: serializer.normalizer, priority: 9 }
