parameters:
    eavmanager_process.process_configuration.class: CleverAge\EAVManager\ProcessBundle\Process\ProcessConfiguration
    eavmanager_process.transformer_configuration.class: CleverAge\EAVManager\ProcessBundle\Transformer\TransformerConfiguration


services:
    eavmanager.process_config.registry:
        class: CleverAge\EAVManager\ProcessBundle\Process\ProcessConfigurationRegistry

    eavmanager.process_manager:
        class: CleverAge\EAVManager\ProcessBundle\Process\ProcessManager

    eavmanager.process.eav_data_source:
        class: CleverAge\EAVManager\ProcessBundle\Process\Generic\EAVDataSourceProcess
        arguments:
            - '@sidus_eav_model.finder'
            - '@sidus_eav_model.family.registry'

    eavmanager.process.normalizer:
        class: CleverAge\EAVManager\ProcessBundle\Process\Generic\NormalizerProcess
        arguments:
            - '@serializer'

    eavmanager.process.denormalizer:
        class: CleverAge\EAVManager\ProcessBundle\Process\Generic\NormalizerProcess
        arguments:
            - '@serializer'
            - false

    eavmanager.transformer_manager:
        class: CleverAge\EAVManager\ProcessBundle\Transformer\TransformerManager

    eavmanager.transformer_config.registry:
        class: CleverAge\EAVManager\ProcessBundle\Transformer\TransformerConfigurationRegistry
