parameters:
    eavmanager_asset.form.media_browser.type.class: CleverAge\EAVManager\AssetBundle\Form\Type\MediaBrowser
    sidus_file_upload.resource.manager.class: CleverAge\EAVManager\AssetBundle\Manager\ResourceManager
    eavmanager_asset.twig.media.extension.class: CleverAge\EAVManager\AssetBundle\Twig\MediaExtension
    eavmanager_asset.doctrine.subscriber.class: CleverAge\EAVManager\AssetBundle\Event\AssetSubscriber

services:
    eavmanager_asset.form.media_browser.type:
        class: '%eavmanager_asset.form.media_browser.type.class%'
        tags:
            - { name: form.type, alias: eavmanager_media_browser }

    eavmanager_asset.twig.media.extension:
        class: '%eavmanager_asset.twig.media.extension.class%'
        arguments:
            - '@liip_imagine.filter.configuration'
        tags:
            - { name: twig.extension }

    eavmanager_asset.doctrine.subscriber:
        class: '%eavmanager_asset.doctrine.subscriber.class%'
        arguments:
            - '%sidus_eav_model.entity.data.class%'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
