parameters:
    oneup_uploader.controller.blueimp.class: CleverAge\EAVManager\AssetBundle\Controller\BlueimpController
    eavmanager_asset.form.media_browser.type.class: CleverAge\EAVManager\AssetBundle\Form\Type\MediaBrowser
    sidus_file_upload.resource.manager.class: CleverAge\EAVManager\AssetBundle\Manager\ResourceManager
    eavmanager_asset.twig.media.extension.class: CleverAge\EAVManager\AssetBundle\Twig\MediaExtension

services:
    eavmanager_asset.form.media_browser.type:
        class: %eavmanager_asset.form.media_browser.type.class%
        tags:
            - { name: form.type, alias: eavmanager_media_browser }

    eavmanager_asset.twig.media.extension:
        class: %eavmanager_asset.twig.media.extension.class%
        arguments:
            - @liip_imagine.filter.configuration
        tags:
            - { name: twig.extension }
