services:
    eavmanager_user.form.user.type:
        class: CleverAge\EAVManager\UserBundle\Form\Type\UserType
        arguments:
            - '@sidus_eav_model.family.registry'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: form.type }

    eavmanager_user.form.group.type:
        class: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
        tags:
            - { name: form.type }

    eavmanager_user.form.user_profile.type:
        parent: eavmanager_user.form.user.type
        class: CleverAge\EAVManager\UserBundle\Form\Type\UserProfileType
        tags:
            - { name: form.type }
