# Routing is configured in app/config/model/admin.yml

eavmanager_admin.wysiwyg.data_selector.media:
    path: /wysiwyg/data-selector/datamedia
    defaults: { _controller: CleverAgeEAVManagerAdminBundle:Wysiwyg:selectMedia }
    options:
        expose: true

eavmanager_admin.wysiwyg.data_selector:
    path: /wysiwyg/data-selector/{configName}
    defaults: { _controller: CleverAgeEAVManagerAdminBundle:Wysiwyg:selectData }
    options:
        expose: true
