parameters:
    eavmanager_admin.listener.routing.cache.class: CleverAge\EAVManager\AdminBundle\Listener\Routing\CacheListener

services:
    eavmanager_admin.listener.routing.cache:
        class: '%eavmanager_admin.listener.routing.cache.class%'
        arguments: ['@sidus_admin.configuration.admin.handler', '@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
