services:
    # Extends base EAV normalizer, injecting imageFile and documentFile when EAV Data is an image or a Document
    sidus_eav_model.normalizer.data:
        parent: serializer.normalizer.object
        class: CleverAge\EAVManager\AssetBundle\Serializer\Normalizer\EAVAssetNormalizer
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.data.ignored_attributes%']]
            - [setReferenceAttributes, ['%sidus_eav_model.normalizer.data.reference_attributes%']]
        tags:
            - { name: serializer.normalizer }

    eavmanager_asset.normalizer.resource:
        parent: serializer.normalizer.object
        class: CleverAge\EAVManager\AssetBundle\Serializer\Normalizer\ResourceNormalizer
        calls:
            - [setResourceManager, ['@sidus_file_upload.resource.manager']]
        tags:
            - { name: serializer.normalizer }
