services:
    eavmanager_api_platform.family_data_provider:
        class: CleverAge\EAVManager\ApiPlatformBundle\DataProvider\FamilyDataProvider
        public: false
        arguments:
            - '@sidus_eav_model.family.registry'
        tags:
            -  { name: api_platform.collection_data_provider, priority: 2 }
            -  { name: api_platform.item_data_provider, priority: 2 }
