sidus_admin:
    fallback_template: CleverAgeEAVManagerAdminBundle:Base
    configurations:
        media:
            controller: CleverAgeEAVManagerAdminBundle:Asset
            entity: '%sidus_data_class%'
            prefix: /medias
            default_form_type: Sidus\EAVBootstrapBundle\Form\Type\TabbedDataType
            actions:
                index:
                    path:     /
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                edit:
                    path:     /{familyCode}/{id}/edit
                delete:
                    path:     /{familyCode}/{id}/delete
                browse:
                    path:     /{familyCode}/browse/{inputId}
                browseThumbnail:
                    path:     /{familyCode}/browseThumbnail/{inputId}
                createModal:
                    path:     /{familyCode}/browse/create/{inputId}
                editModal:
                    path:     /{familyCode}/browse/{id}/edit/{inputId}
            options:
                families:
                    Image: ~
                    Document: ~

        resource:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\EAVManager\AssetBundle\Entity\Document
            prefix: /resources
            actions:
                list:
                    path: /
                index:
                    path: /
                delete:
                    path: /{id}/delete

        user:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\User
            prefix: /users
            default_form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
            base_template: CleverAgeEAVManagerAdminBundle:User:index.html.twig
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                edit:
                    path:     /{id}/edit
                delete:
                    path:     /{id}/delete
                resetPassword:
                    path:     /{id}/reset-password

        group:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\Group
            prefix: /groups
            default_form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
            base_template: CleverAgeEAVManagerAdminBundle:User:index.html.twig
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                edit:
                    path:     /{id}/edit
                delete:
                    path:     /{id}/delete

        variant:
            controller: CleverAgeEAVManagerAdminBundle:Variant
            entity: '%sidus_data_class%'
            prefix: /variant
            default_form_type: Sidus\EAVVariantBundle\Form\Type\VariantType
            actions:
                select:
                    path:     /{attribute}/{parentId}/select
                    form_type: eavmanager_variant_family_selector
                create:
                    path:     /{attribute}/{parentId}/{familyCode}/create
                edit:
                    path:     /{attribute}/{parentId}/{familyCode}/{id}/edit
                delete:
                    path:     /{attribute}/{parentId}/{familyCode}/{id}/delete
            options:
                datagrid: base
