sidus_eav_model:
    families:
        BaseAsset:
            instantiable: false
            attributeAsLabel: title
            attributes:
                title:
                    group: content
                    required: true
                fileSize:
                    group: meta
                    type: integer
                    form_options:
                        disabled: true
                mimeType:
                    group: meta
                    form_options:
                        disabled: true
                fileName:
                    group: meta
                    form_options:
                        disabled: true
                tags:
                    group: content
                    multiple: true

        Image:
            parent: BaseAsset
            attributeAsLabel: title
            attributes:
                imageFile: ~
                altText:
                    group: meta
                    form_options:
                        help_block: 'Laisser vide pour utiliser le titre'
                copyright:
                    group: meta

        Document:
            parent: BaseAsset
            attributeAsLabel: title
            attributes:
                documentFile: ~

    attributes:
        # Relations : Use them in your custom families
        image:
            group: content
            type: media_browser
            options:
                allowed_families:
                    - Image

        images:
            group: content
            type: media_browser
            multiple: true
            options:
                allowed_families:
                    - Image

        document:
            group: content
            type: media_browser
            options:
                allowed_families:
                    - Document

        documents:
            group: content
            type: media_browser
            multiple: true
            options:
                allowed_families:
                    - Document

        # Custom Attributes => link to uploaded file
        documentFile:
            group: content
            type: document
            required: true

        imageFile:
            group: content
            required: true
            type: image
