sidus_eav_model:
    families:
        BaseAsset:
            instantiable: false
            attributeAsLabel: title
            attributes:
                - title
                - fileSize
                - mimeType
                - fileName

        Image:
            parent: BaseAsset
            attributeAsLabel: title
            attributes:
                - imageFile
                - link
                - tags

        Document:
            parent: BaseAsset
            attributeAsLabel: title
            attributes:
                - documentFile

    attributes:
        # Relations
        image:
            group: content
            type: media_browser
            form_options:
                family: Image

        document:
            group: content
            type: media_browser
            form_options:
                family: Document

        # Custom Attributes => link to uploaded file
        documentFile:
            group: content
            type: document
            required: true

        imageFile:
            group: content
            required: true
            type: image

        # Locked attributes (automatically filled from file upload)
        fileSize:
            group: content
            type: integer
            form_options:
                disabled: true

        mimeType:
            group: content
            form_options:
                disabled: true

        fileName:
            group: content
            form_options:
                disabled: true

        # Attributes
        link:
            group: content

        tags:
            group: content
            multiple: true

        altText:
            group: content
            form_options:
                help_block: 'Laisser vide pour utiliser le titre'

        legend:
            group: content

        copyright:
            group: content
