sidus_eav_model:
    families:
        BaseAsset:
            instantiable: false
            attributeAsLabel: title
            attributes:
                title:
                    group: content
                    required: true
                fileSize:
                    group: meta
                    type: integer
                    form_options:
                        disabled: true
                mimeType:
                    group: meta
                    form_options:
                        disabled: true
                fileName:
                    group: meta
                    form_options:
                        disabled: true
                tags:
                    group: content
                    multiple: true

        Image:
            parent: BaseAsset
            attributeAsLabel: title
            attributes:
                imageFile:
                    group: content
                    required: true
                    type: image
                altText:
                    group: meta
                    form_options:
                        help_block: 'Laisser vide pour utiliser le titre'
                copyright:
                    group: meta

        Document:
            parent: BaseAsset
            attributeAsLabel: title
            attributes:
                documentFile:
                    group: content
                    type: document
                    required: true
