sidus_data_grid:
    configurations:
        user:
            filter_config:
                entity: CleverAgeEAVManagerUserBundle:User
                sortable:
                    - id
                    - createdAt
                    - username
                    - email
                fields:
                    createdAt:
                        type: date_range
                        label: Création
                    email: ~
                    username: ~
            columns:
                id:
                    label: '#'
                username: ~
                email: ~
                lastName:
                    property_path: data.lastName
                firstName:
                    property_path: data.firstName
                roles: ~
                createdAt: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:User:partials/list.row.actions.html.twig
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_right"

        group:
            filter_config:
                entity: CleverAgeEAVManagerUserBundle:Group
                sortable:
                    - id
                    - createdAt
                    - name
                    - roles
                fields:
                    createdAt:
                        type: date_range
                        label: Création
                    name: ~
            columns:
                id:
                    label: '#'
                name: ~
                roles: ~
                createdAt: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Base:partials/list.row.actions.html.twig
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_right"

        resource:
            filter_config:
                entity: CleverAge\EAVManager\AssetBundle\Entity\Document
                sortable:
                    - id
                    - originalFileName
                    - fileSize
                    - fileType
                    - fileModifiedAt
                fields:
                    originalFileName: ~
                    fileType:
                        type: choice
                    fileModifiedAt:
                        type: date_range
            columns:
                id:
                    label: '#'
                originalFileName: ~
                type: ~
                fileSize: ~
                fileType: ~
                fileModifiedAt: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Asset/partials:resource.row.actions.html.twig
