sidus_eav_model:
    collection_type: Sidus\EAVBootstrapBundle\Form\Type\BootstrapCollectionType

sidus_publishing:
    enabled: false
    queue:
        base_directory: '%kernel.root_dir%/../var/publishing'
        lockfile:       '%kernel.root_dir%/../var/publishing/.lock'
        override_timeout: 60
    publishers: {}

mopa_bootstrap:
    form:
        render_required_asterisk: true
        render_optional_text: false
