sidus_eav_data_grid:
    configurations:
        baseasset:
            family: BaseAsset
            filter_config:
                sortable:
                    - id
                    - createdAt
                    - updatedAt
                fields: []
            columns:
                id:
                    label: '#'
                label:
                    template: CleverAgeEAVManagerAdminBundle:Base:clickable.column.html.twig
                createdAt: ~
                updatedAt: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Data:list.row.actions.html.twig
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_right"
            reset_button:
                attr:
                    data-target-element: "#tg_center"

        document:
            family: Document
            parent: baseasset
            filter_config:
                sortable:
                    - id
                    - title
                    - mimeType
                    - fileName
                fields:
                    title: ~
                    fileName: ~
                    mimeType:
                        type: choice
            columns:
                id:
                    label: '#'
                title:
                    template: CleverAgeEAVManagerAdminBundle:Base:clickable.column.html.twig
                fileSize: ~
                mimeType: ~
                fileName: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Data:list.row.actions.html.twig

        image:
            family: Image
            parent: baseasset
            filter_config:
                sortable:
                    - id
                    - title
                    - mimeType
                fields:
                    title: ~
                    tags: ~
                    fileName: ~
                    mimeType:
                        type: choice
            columns:
                id:
                    label: '#'
                imageFile:
                    template: CleverAgeEAVManagerAdminBundle:Asset:browse.thumbnail.html.twig
                title:
                    template: CleverAgeEAVManagerAdminBundle:Base:clickable.column.html.twig
                tags: ~
                mimeType: ~
                filename:
                    property_path: imageFile.originalFilename
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Data:list.row.actions.html.twig

        image_browser:
            family: Image
            filter_config:
                results_per_page: 5
                sortable:
                    - id
                    - title
                fields:
                    title: ~
                    tags: ~
            columns:
                id:
                    label: '#'
                imageFile:
                    template: CleverAgeEAVManagerAdminBundle:Asset:browse.thumbnail.html.twig
                title:
                    template: CleverAgeEAVManagerAdminBundle:Asset:browse.row.label.html.twig
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Asset:browse.row.actions.html.twig
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: createModal
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_modal"
                browseThumbnail:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.browseThumbnail.label
                    action: browseThumbnail
                    icon: th
                    attr:
                        class: btn-default
                        data-target-element: "#tg_modal"
            reset_button:
                attr:
                    data-target-element: "#tg_modal"

        thumbnail_browser:
            family: Image
            filter_config:
                results_per_page: 18
                sortable: []
                fields:
                    title: ~
                    tags: ~
            columns: {}
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: createModal
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_modal"
                browse:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.browse.label
                    action: browse
                    icon: list
                    attr:
                        class: btn-default
                        data-target-element: "#tg_modal"
            reset_button:
                attr:
                    data-target-element: "#tg_modal"
