sidus_eav_model:
    collection_type: Sidus\EAVBootstrapBundle\Form\Type\BootstrapCollectionType
    default_context: []

sidus_eav_variant:
    routes:
        select: admin.variant.select
        create: admin.variant.create
        edit: admin.variant.edit
        delete: admin.variant.delete
    families: ~

sidus_publishing:
    enabled: false
    queue:
        base_directory: '%kernel.root_dir%/../var/publishing'
        lockfile:       '%kernel.root_dir%/../var/publishing/.lock'
        override_timeout: 60
    publishers: {}

mopa_bootstrap:
    form:
        render_required_asterisk: true
        render_optional_text: false
