services:
    eavmanager_process.task.eav_reader:
        class: CleverAge\EAVManager\ProcessBundle\Task\EAVReaderTask
        shared: false
        arguments:
            - '@doctrine'
            - '@sidus_eav_model.family.registry'