services:
    eavmanager_admin.form.link.type:
        class: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
        arguments: ['@sidus_admin.routing.admin_router']
        tags:
          - { name: form.type }

    eavmanager_admin.form.image.type:
        class: CleverAge\EAVManager\AdminBundle\Form\Type\ImageType
        tags:
          - { name: form.type }

    eavmanager_admin.form.variant_family_selector.type:
        class: CleverAge\EAVManager\AdminBundle\Form\Type\VariantFamilySelector
        tags:
          - { name: form.type }
