sidus_admin:
    configurations:
        _data:
            controller: CleverAgeEAVManagerAdminBundle:InlineEAVData
            entity: '%sidus_data_class%'
            prefix: /_data
            actions:
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                read:
                    path:     /{familyCode}/read/{id}
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/edit/{id}
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/delete/{id}
                editInline:
                    path:     /edit/{id}
                    form_type: '%eav_form.type%'
                preview:
                    path:     /preview/{id}
                    form_type: '%eav_form.type%'
                    form_options:
                        disabled: true
                        show_legend: false
            options:
                hidden: true
