sidus_admin:
    configurations:
        group:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\Group
            prefix: /groups
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
                read:
                    path:     /read/{id}
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
                edit:
                    path:     /edit/{id}
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
                delete:
                    path:     /delete/{id}
            options:
                hidden: true
