sidus_admin:
    configurations:
        media:
            controller: '%eav.controller%'
            entity: '%sidus_data_class%'
            prefix: /medias
            actions:
                list:
                    path:     /{familyCode}/list
                read:
                    path:     /{familyCode}/{id}/read
                    form_type: '%eav_form.type%'
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/{id}/edit
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                hidden: true
                icon: image
                families:
                    Image: ~
                    Document: ~
