sidus_admin:
    configurations:
        process:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\ProcessBundle\Entity\ProcessHistory
            prefix: /process
            actions:
                list:
                    path: /
                delete:
                    path: /delete/{id}
            options:
                icon: history
                hidden: true
