sidus_admin:
    configurations:
        task:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\ProcessBundle\Entity\TaskHistory
            prefix: /task
            actions:
                list:
                    path: /
                show:
                    path: /{id}/show
                delete:
                    path: /{id}/delete
            options:
                icon: tasks
                hidden: true
