sidus_admin:
    configurations:
        task:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\ProcessBundle\Entity\TaskHistory
            prefix: /task
            actions:
                list:
                    path: /
                delete:
                    path: /delete/{id}
            options:
                icon: tasks
                hidden: true
