sidus_admin:
    configurations:
        user:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\User
            prefix: /users
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                read:
                    path:     /read/{id}
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                edit:
                    path:     /edit/{id}
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                delete:
                    path:     /delete/{id}
                resetPassword:
                    path:     /reset-password/{id}
            options:
                hidden: true
