sidus_admin:
    configurations:
        user:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\User
            prefix: /users
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                edit:
                    path:     /{id}/edit
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                delete:
                    path:     /{id}/delete
                resetPassword:
                    path:     /{id}/reset-password
            options:
                hidden: true
