sidus_data_grid:
    configurations:
        process:
            query_handler:
                provider: doctrine
                options:
                    entity: CleverAge\ProcessBundle\Entity\ProcessHistory
                sortable:
                    - processCode
                    - startDate
                    - endDate
                    - state
                default_sort:
                    startDate: DESC
                filters:
                    processCode:
                        type: choice
                    startDate:
                        type: date_range
                    endDate:
                        type: date_range
                    state:
                        type: choice
            columns:
                processCode: ~
                startDate: ~
                endDate: ~
                state: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Process/partials:process.row.actions.html.twig
