sidus_data_grid:
    configurations:
        task:
            query_handler:
                provider: doctrine
                options:
                    entity: CleverAge\ProcessBundle\Entity\TaskHistory
                results_per_page: 50
                sortable:
                    - taskCode
                    - message
                    - loggedAt
                    - level
                    - reference
                default_sort:
                    loggedAt: DESC
                filters:
#                    processHistory:
#                        type: choice
#                        form_options:
#                            multiple: true
                    taskCode:
                        type: choice
                    message: ~
                    loggedAt:
                        type: date_range
                    level:
                        type: choice
                    reference: ~
            columns:
                processCode:
                    property_path: processHistory.processCode
                taskCode:
                message: ~
                loggedAt: ~
                level: ~
                reference: ~
                context: ~
