eavmanager_user:
    resource: '@CleverAgeEAVManagerUserBundle/Controller'
    type:     annotation

logout:
    path: /logout

eavmanager_user.profile:
    resource: routing/user.yml
    prefix: /profile
