parameters:
    eavmanager_user.form.user.type.class: CleverAge\EAVManager\UserBundle\Form\Type\UserType
    eavmanager_user.form.group.type.class: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
    eavmanager_user.form.user_profile.type.class: CleverAge\EAVManager\UserBundle\Form\Type\UserProfileType
    eavmanager_user.doctrine.event.authorable.subscriber.class: CleverAge\EAVManager\UserBundle\Event\AuthorableSubscriber
    eavmanager_user.mailer.class: CleverAge\EAVManager\UserBundle\Mailer\Mailer

services:
    eavmanager_user.form.user.type:
        class: %eavmanager_user.form.user.type.class%
        arguments: [@sidus_eav_model.family.User, @security.token_storage, @security.authorization_checker]
        tags:
            - { name: form.type, alias: eavmanager_user }

    eavmanager_user.form.group.type:
        class: %eavmanager_user.form.group.type.class%
        tags:
            - { name: form.type, alias: eavmanager_group }

    eavmanager_user.form.user_profile.type:
        parent: eavmanager_user.form.user.type
        class: %eavmanager_user.form.user_profile.type.class%
        tags:
            - { name: form.type, alias: eavmanager_user_profile }

    eavmanager_user.doctrine.event.authorable.subscriber:
        class: %eavmanager_user.doctrine.event.authorable.subscriber.class%
        arguments: [@security.token_storage]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    eavmanager_user.mailer:
        class: %eavmanager_user.mailer.class%
        arguments: [@mailer, %mailer_sender%, @twig]
